version: '3.8'

services:
  api:
    build:
      context: .
    volumes:
      # Sincroniza o código local com o container para hot-reloading
      - .:/usr/src/app
      # Ignora a pasta node_modules dentro do container
      - /usr/src/app/node_modules
    # Sobrescreve o CMD do Dockerfile para rodar em modo dev
    command: sh -c "npm install && npm run start:dev"
